name: publish to crates.io

on:
  release:
    types: [released]

jobs:
  release:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: login 
        run: cargo login ${{ secrets.CARGO_API_TOKEN }}
      - name: publish
        run: cargo publish
        
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: login ${{ secrets.CARGO_API_TOKEN }}
      - uses: actions-rs/cargo@v1
        with:
          command: publish
